### ISSUE TITLE
extend it to report the PoE status of a port?

### ISSUE THREAD

**Issue by gramels** [jonbulica99/zyxel-poe-manager#1]
Hi,

thanks a lot for this script.
Enables me to integrate it into my fhem based automation.

Do you see a chance to extend it to report the PoE status of a port?

Cheers! 

-gramels

**Comment by jonbulica99** [comment]
Hey @gramels, glad you found this useful!
I could probably implement what you are asking. It simply involves querying `http://zyxel-ip-address/cgi-bin/dispatcher.cgi?cmd=773`. This returns a HTML table (yikes) with a lot of data for every port (e.g. priority, power consumption etc.)
Do you need all of the data, or just the port state?

**Comment by gramels** [comment]
Hi Jon,
thanks for your answer.

status would be most important
consumption would be nice
all others optional at the moment.

**Comment by jonbulica99** [comment]
Hey @gramels, I just pushed a new version with the changes you requested. Do you mind testing it and giving me a short feedback; e.g. whether it works on your switch?

Regards,
Jon

**Comment by desmond206x** [comment]
Hi @jonbulica99 !
Thank you for this script. I just found it after searching hours to find out that the 1900 doens't support poe switching over snmp...

The command with port 0 to get all the information about all ports works fine!

The script also works perfectly with my GS1900-24HP and with the current firmware version V2.50(AAHM.0) | 10/21/2019

Thanks again!
