### ISSUE TITLE
disable/enable the lan port instead of poe?

### ISSUE THREAD

**Issue by Jasimo** [jonbulica99/zyxel-poe-manager#2]
Hi.

Is it possible to simply disable/enable the lan port instead of poe? It would be great if you could give me a tip on how to adapt your script for this. I want to use it on an GS1900-24E.

**Comment by jonbulica99** [comment]
Hey, sorry for the late reply - I was on vacation. That being said you should be able to modify the functionality by editing the following lines

https://github.com/jonbulica99/zyxel-poe-manager/blob/003fa57e3ef9643aae6ff0e090f77eddc95c8227/poe-manager.py#L76-L85

to something like this: 

```python
 "XSSID": xssid_content, 
 "portlist": args.port, 
 "state": args.state, 
 "descp": "",
 "speed": 0,
 "duplex": 0,
 "fc": 0,
 "cmd": 770,
 "sysSubmit": "Apply"
```

You may be able to omit some options (speed, duplex etc.) but I haven't tested it.
