### ISSUE TITLE
PD Priority

### ISSUE THREAD

**Issue by Oekel** [jonbulica99/zyxel-poe-manager#3]
Just tested sucessfully on a "GS1900-24HP"
Only thing that is anoying is that every change of state will also set 'PD Priority': 'Medium'.

(maybee I can fix on my own, but just lerning python ;)

**Comment by jonbulica99** [comment]
This is the correspondig line that changes the priority:

https://github.com/jonbulica99/zyxel-poe-manager/blob/003fa57e3ef9643aae6ff0e090f77eddc95c8227/poe-manager.py#L79

Maybe try removing it completely or changing it to another number and see what it does.
