### ISSUE TITLE
auth failure with firmware V2.70(AAZI.1)C0

### ISSUE THREAD

**Issue by lukasleuenberger** [jonbulica99/zyxel-poe-manager#4]
hi

just for your info: i just upgraded my switch to the latest firmware (GS1900-10HP_V2.70(AAZI.1)C0) and with this firmware, the auth process from your script seems to be broken:

Traceback (most recent call last):
  File "/config/python_scripts/poe-manager.py", line 145, in <module>
    main(parser.parse_args())
  File "/config/python_scripts/poe-manager.py", line 35, in main
    raise Exception("Login failed: %s" % ret2.text)
Exception: Login failed:
Not Auth

according zyxel's changelog for the v2.70 release there were some changes within the auth process. for the moment i switched back to v2.60 and it works again as expected.

**Comment by jonbulica99** [comment]
The latest release should support the new firmware version: [v0.4](https://github.com/jonbulica99/zyxel-poe-manager/releases/tag/v0.4)
They mess with the authentication on every release, this time it was a rather big refactoring.
