### ISSUE TITLE
Zyxel GS1920-48HP

### ISSUE THREAD

**Issue by Misak** [jonbulica99/zyxel-poe-manager#5]
Hello, I tried this script on Zyxel GS1920-48HP and it is not working for me. Any chance to change the script so it would work also with 1920? It would help me a lot. Thanks.
```
Traceback (most recent call last):
  File "poe-manager.py", line 144, in <module>
    main(parser.parse_args())
  File "poe-manager.py", line 34, in main
    raise Exception("Login failed: %s" % ret2.text)
Exception: Login failed: <html>
<head>
<title>Object Not Found</title>
</head>
<body>
<h1>Object Not Found</h1>
The requested URL '/cgi-bin/dispatcher.cgi?login_chk=1&dummy=1653921839518' was not found on the RomPager server.<p>
Return to <A HREF="">last page</A><p>

</body>
</html>
```

**Comment by jonbulica99** [comment]
Hi, unfortunately I don't own a GS1920-48HP, so I cannot test anything. You could probably make the script work with it if you have a bit of python and web skills and make the necessary adjustments.
I just released a new version for firmware `V2.70`, if your switch has the same firmware it might just work without any adjustments idk.
